version: 2.0

#### YAML ANCHORS INSTEAD OF COMMANDS # while version 2.1 already supports commands, the local runner doesn't. When it does, we can upgrade.

git-submodules: &git-submodules
  run:
    name: "Pull Submodules"
    command: |
      git submodule init
      git submodule update

upload-coverage: &upload-coverage
  run:
    name: Upload test coverage to Codecov
    command: bash <(curl -s https://codecov.io/bash)

store-junit-results: &store-junit-test-results
  store_test_results:
    path: tmp/junit

store-test-artifacts: &store-test-artifacts
  store_artifacts:
    path: tmp/junit
    destination: junit

store-log-artifacts: &store-log-artifacts
  store_artifacts:
    path: log/test.log
    destination: test.log

restore-bundler-cache: &restore-bundler-cache
  restore_cache:
    keys:
      - v1-bundler-gems-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
restore-npm-cache: &restore-npm-cache
  restore_cache:
    keys:
      - v1-npm-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

attach-to-workspace: &attach-to-workspace
  attach_workspace:
    at: .

system-builder: &system-builder
  image: quay.io/3scale/system-builder:latest
  environment:
    BUNDLE_FROZEN: true
    BUNDLE_PATH: 'vendor/bundle'
    DISABLE_SPRING: "true"
    ORACLE_SYSTEM_PASSWORD: threescalepass
    NLS_LANG: AMERICAN_AMERICA.UTF8
    TZ: UTC
    MASTER_PASSWORD: p
    USER_PASSWORD: p

mysql-container: &mysql-container
  image: circleci/mysql:5.7-ram
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_ROOT_PASSWORD: ''
    MYSQL_DATABASE: circleci

oracle-db-container: &oracle-db-container
  image: quay.io/3scale/oracle:12.2.0.1-ee-scripted
  auth:
    username: $DOCKER_USER
    password: $DOCKER_PASS
  environment:
    ORACLE_CHARACTERSET: 'AL32UTF8'
    ORACLE_SID: 'threescale'
    ORACLE_PDB: 'systempdb'
    ORACLE_PWD: 'threescalepass'
  command: |
    bash -c "sed -i.bak 's|2048|6144|g' /opt/oracle/dbca.rsp.tmpl && exec /opt/oracle/runOracle.sh"

clone-oracle-libs: &clone-oracle-libs
  run:
    name: "Fetch oracle libraries"
    command: |
      git clone git@github.com:3scale/system-libraries.git
      cp -R system-libraries/vendor/oracle/*.zip vendor/oracle
      sudo unzip vendor/oracle/instantclient-basiclite-linux.x64-12.2.0.1.0.zip -d /opt/oracle
      sudo unzip vendor/oracle/instantclient-sdk-linux.x64-12.2.0.1.0.zip -d /opt/oracle
      sudo unzip vendor/oracle/instantclient-odbc-linux.x64-12.2.0.1.0-2.zip -d /opt/oracle
      sudo ln -s /opt/oracle/instantclient_12_2/libclntsh.so.12.1 /opt/oracle/instantclient_12_2/libclntsh.so
      sudo rm -rf /opt/system/vendor/oracle
      rm -rf vendor/oracle/*.zip

jobs:
  dependencies_bundler:
    docker:
      - *system-builder
    steps:
      - checkout
      - *git-submodules
      - *restore-bundler-cache
      - run:
          name: Install gems with bundler
          command: make bundle
          environment:
            BUNDLE_RETRY: 3
            BUNDLE_JOBS: 3
      - save_cache:
          key: v1-bundler-gems-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
            - ./.bundle/
      - persist_to_workspace:
          root: .
          paths:
          - ./vendor/bundle
          - ./.bundle/
  dependencies_npm:
    docker:
      - *system-builder
    steps:
      - checkout
      - *git-submodules
      - *restore-npm-cache
      - run:
          name: Install NPM dependencies
          command: make npm-install
      - save_cache:
          key: v1-npm-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./assets/jspm_packages
            - ./.jspm
      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules
            - ./assets/jspm_packages
            - ./.jspm

  assets_precompile:
    docker:
      - *system-builder
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - run:
          name: Precompile assets
          command: make precompile-assets
          environment:
            RAILS_GROUPS: assets 
      - persist_to_workspace:
          root: .
          paths:
            - ./public/assets
            - ./config/*.yml

  lint:
    docker:
      - *system-builder
      - *mysql-container
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - run:
          name: Start Xvfb
          command: Xvfb :99 -screen 0 1280x1024x24
          background: true
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - run:
          name: Licences check
          command: make test-rake JOB="ci:license_finder:run"
      - run:
          name: Swagger validation
          command: make test-rake JOB="doc:swagger:validate:all doc:swagger:generate:all"
      - run:
          name: JSPM
          command: make test-rake JOB="ci:jspm"
      - run:
          name: Yarn test
          command: make test-rake JOB="integrate:frontend"
      - *store-junit-test-results
      - *store-test-artifacts
      - store_artifacts:
          path: doc/licenses
          destination: licenses
      - store_artifacts:
          path: doc/active_docs
          destination: active_docs
      - *upload-coverage

  unit:
    parallelism: 8
    resource_class: small
    docker:
      - *system-builder
      - *mysql-container
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - run:
          name: Rails tests
          command: make test-rake JOB="integrate:unit"
      - *store-junit-test-results
      - *store-test-artifacts
      - *store-log-artifacts
      - *upload-coverage

  unit-oracle:
    parallelism: 4
    resource_class: large
    docker:
      - *system-builder
      - *oracle-db-container
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - add_ssh_keys:
          fingerprints:
          - "36:6a:7a:93:88:52:12:dd:4c:84:3a:42:bf:8c:c3:58"
      - *clone-oracle-libs
      - run:
          name: Rails tests
          command: make boot_database test-rake JOB="integrate:unit" DB=oracle
      - *store-junit-test-results
      - *store-test-artifacts
      - *store-log-artifacts
      - *upload-coverage

  functional:
    parallelism: 2
    resource_class: small
    docker:
      - *system-builder
      - *mysql-container
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - run:
          name: Rails tests
          command: make test-rake JOB="integrate:functional"
          environment:
            LC_ALL: en_US.UTF-8
      - *store-junit-test-results
      - *store-test-artifacts
      - *store-log-artifacts
      - *upload-coverage
  functional-oracle:
    parallelism: 2
    resource_class: large
    docker:
      - *system-builder
      - *oracle-db-container
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - add_ssh_keys:
          fingerprints:
          - "36:6a:7a:93:88:52:12:dd:4c:84:3a:42:bf:8c:c3:58"
      - *clone-oracle-libs
      - run:
          name: Rails tests
          command: make boot_database test-rake JOB="integrate:functional" DB=oracle
          environment:
            LC_ALL: en_US.UTF-8
      - *store-junit-test-results
      - *store-test-artifacts
      - *store-log-artifacts
      - *upload-coverage
  integration:
    parallelism: 8
    resource_class: small
    docker:
      - *system-builder
      - *mysql-container
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - run:
          name: Rails tests
          command: make test-rake JOB="integrate:integration"
      - *store-junit-test-results
      - *store-test-artifacts
      - *store-log-artifacts
      - *upload-coverage
  integration-oracle:
    parallelism: 6
    resource_class: large
    docker:
      - *system-builder
      - *oracle-db-container
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - add_ssh_keys:
          fingerprints:
          - "36:6a:7a:93:88:52:12:dd:4c:84:3a:42:bf:8c:c3:58"
      - *clone-oracle-libs
      - run:
          name: Rails tests
          command: make boot_database test-rake JOB="integrate:integration" DB=oracle
      - *store-junit-test-results
      - *store-test-artifacts
      - *store-log-artifacts
      - *upload-coverage
  rspec:
    parallelism: 3
    resource_class: small
    docker:
      - *system-builder
      - *mysql-container
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - run:
          name: Rspec tests
          command: make test-rake JOB="integrate:rspec"
      - *store-junit-test-results
      - *store-test-artifacts
      - *store-log-artifacts
      - *upload-coverage
  rspec-oracle:
    parallelism: 4
    resource_class: large
    docker:
      - *system-builder
      - *oracle-db-container
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - add_ssh_keys:
          fingerprints:
          - "36:6a:7a:93:88:52:12:dd:4c:84:3a:42:bf:8c:c3:58"
      - *clone-oracle-libs
      - run:
          name: Rspec tests
          command: make boot_database test-rake JOB="integrate:rspec" DB=oracle
      - *store-junit-test-results
      - *store-test-artifacts
      - *store-log-artifacts
      - *upload-coverage

  cucumber:
    parallelism: 40
    resource_class: small
    docker:
      - *system-builder
      - image: quay.io/mikz/dnsmasq
        command:
        - --no-poll
        - --address=/#/127.0.0.1
      - *mysql-container
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - run:
          name: Run cucumber javascript tests
          command: make test-rake JOB="integrate:cucumber" PROXY_ENABLED=true
      - run:
          name: Restore internet access
          command: |
            sudo make dnsmasq_unset
          when: always
      - *store-junit-test-results
      - *store-test-artifacts
      - *store-log-artifacts
      - store_artifacts:
          path: tmp/capybara
          destination: capybara
      - *upload-coverage
  cucumber-oracle:
    parallelism: 30
    resource_class: large
    docker:
      - *system-builder
      - image: quay.io/mikz/dnsmasq
        command:
        - --no-poll
        - --address=/#/127.0.0.1
      - *mysql-container
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - add_ssh_keys:
          fingerprints:
          - "36:6a:7a:93:88:52:12:dd:4c:84:3a:42:bf:8c:c3:58"
      - *clone-oracle-libs
      - run:
          name: Run cucumber javascript tests
          command: make boot_database test-rake JOB="integrate:cucumber" PROXY_ENABLED=true DB=oracle
      - run:
          name: Restore internet access
          command: |
            make dnsmasq_unset
          when: always
      - *store-junit-test-results
      - *store-test-artifacts
      - *store-log-artifacts
      - store_artifacts:
          path: tmp/capybara
          destination: capybara
      - *upload-coverage

  docker-build:
    resource_class: small
    docker:
      - image: docker:stable
        environment:
          DOCKER_COMPOSE: /usr/bin/docker-compose
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build System Container Image for OpenShift
          command: |
            cd openshift/system
            docker build --build-arg=BUNDLER_ENV="$(env | grep -e ^BUNDLE_)" --file Dockerfile ../..
            docker build --file Dockerfile.on_prem --pull ../..

workflows:
  version: 2
  mysql_build:
    jobs:
      - dependencies_bundler
      - dependencies_npm
      - docker-build:
          context: org-global
      - assets_precompile:
          requires:
            - dependencies_bundler
            - dependencies_npm

      - lint:
          requires:
            - assets_precompile
      - unit:
          requires:
            - dependencies_bundler
      - functional:
          requires:
            - assets_precompile
      - integration:
          requires:
            - assets_precompile
      - rspec:
          requires:
            - dependencies_bundler
      - cucumber:
          requires:
            - assets_precompile
  oracle_build:
    jobs:
      - manual_approval: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
        # On approval of the `hold` job, any successive job that requires the `hold` job will run.
      - dependencies_bundler:
          requires:
          - manual_approval
      - dependencies_npm:
          requires:
          - manual_approval
      - docker-build:
          context: org-global
          requires:
          - manual_approval
      - assets_precompile:
          requires:
            - dependencies_bundler
            - dependencies_npm

      - lint:
          requires:
            - assets_precompile
      - unit-oracle:
          requires:
            - dependencies_bundler
      - functional-oracle:
          requires:
            - assets_precompile
      - integration-oracle:
          requires:
            - assets_precompile
      - rspec-oracle:
          requires:
            - dependencies_bundler
      - cucumber-oracle:
          requires:
            - assets_precompile
